version: '3.1'

services:
  db:
    image: mysql
    container_name: employee-management-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EMPLOYEE_MANAGEMENT
    volumes:
      - ./storage:/var/lib/mysql